apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: groundbreaker-cloud-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: groundbreaker
              operator: In
              values:
                - cloud
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: groundbreaker-cloud
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: groundbreaker-cloud-placement
      requeueAfterSeconds: 30
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
      name: groundbreaker-cloud-{{name}}
    spec:
      destination:
        namespace: groundbreaker-prod
        server: '{{server}}'
      project: default
      source:
        path: deploy/cloud
        repoURL: https://github.com/kincl/multicluster-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
        retry:
          limit: 10
          backoff:
            duration: 1m
