apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-ingress
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: letsencrypt-ingress
  duration: 2160h0m0s # 90d
  renewBefore: 720h0m0s # 30d is recommended by LE
  commonName: PLACEHOLDER
  usages:
    - server auth
    - client auth
  dnsNames: []
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
