apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: jkincl@redhat.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z26B5S9YMB3IDU
          region: us-east2
          secretAccessKeySecretRef:
            name: cloud-credentials
            key: aws_secret_access_key
          accessKeyIDSecretRef:
            name: cloud-credentials
            key: aws_access_key_id
