apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# install
- namespace.yaml
- operatorgroup.yaml
- subscription.yaml

# configure
- certmanager.yaml
- clusterissuer.yaml
- credentialrequest.yaml

# issue
- certificate-api.yaml
- certificate-ingress.yaml

# deploy
- ingresscontroller.yaml
- apiserver.yaml
