apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: cert-manager-azure
  namespace: openshift-cloud-credential-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings:
      - role: Contributor
  secretRef:
    name: cloud-credentials
    namespace: cert-manager
  serviceAccountNames:
  - cert-manager