apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - google:
      clientID: clientid
      clientSecret:
        name: google-client-secret # created by secret-management/secrets.yaml
      hostedDomain: redhat.com
    mappingMethod: claim
    name: google
    type: Google
